package twarehouse.molde.estoque;

import java.io.Serializable;

import javax.enterprise.inject.Vetoed;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pcp
//  @ File Name : Almoxarifado.java
//  @ Date : 15/09/2015
//  @ Author : Sidronio Lima
//
//

@Entity
@Table(name="almoxarifado")
@Vetoed
public class Almoxarifado implements Serializable {

	private static final long serialVersionUID = -4283736669472993284L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long codigo;
	
	@Column(length=60)
	private String descricao;
	
	@Column(length=60)
	private String localizacao;
	
	public Almoxarifado() {	}
	
	public Almoxarifado(Long codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao; 
	}
	
	public String codigoFormatado(){
		
		if (null == codigo) {
			return "";
		}
		
		return String.format("%02d", this.codigo);
	}
	
	public Long getCodigo() {
		return codigo;
	}
	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getLocalizacao() {
		return localizacao;
	}
	public void setLocalizacao(String localizacao) {
		this.localizacao = localizacao;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigo == null) ? 0 : codigo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Almoxarifado other = (Almoxarifado) obj;
		if (codigo == null) {
			if (other.codigo != null)
				return false;
		} else if (!codigo.equals(other.codigo))
			return false;
		return true;
	}

}
